"""Sheet schemas for the lean Kamandal V2 cockpit."""

from __future__ import annotations

UNIVERSE_HEADER = [
    "symbol",
    "enabled",
    "profile",
    "tradable_iv_percentile_min",
    "tradable_iv_percentile_max",
    "max_bpr_pct",
    "max_positions",
    "earnings_sensitive",
    "event_avoid_days_before",
    "event_avoid_days_after",
    "allowed_playbooks",
    "notes",
]

PLAYBOOKS_HEADER = [
    "playbook_id",
    "enabled",
    "strategy_family",
    "structure",
    "variant",
    "leg_count",
    "profiles",
    "iv_percentile_min",
    "iv_percentile_max",
    "dte_min",
    "dte_max",
    "short_delta_min",
    "short_delta_max",
    "long_delta_min",
    "long_delta_max",
    "spread_width",
    "min_credit_to_width_ratio",
    "max_debit_pct_bpr",
    "profit_target_pct",
    "max_loss_multiple",
    "exit_dte_min",
    "half_time_exit",
    "avoid_earnings",
    "notes",
]

DAILY_PLAN_HEADER = [
    "plan_date",
    "plan_rank",
    "plan_id",
    "plan_status",
    "plan_trade_count",
    "plan_score",
    "plan_summary",
    "trade_bundle",
    "plan_total_bpr",
    "plan_bpr_utilization_pct",
    "buying_power_after",
    "portfolio_delta_before",
    "portfolio_delta_after",
    "portfolio_delta_change",
    "portfolio_gamma_before",
    "portfolio_gamma_after",
    "portfolio_gamma_change",
    "portfolio_theta_before",
    "portfolio_theta_after",
    "portfolio_theta_change",
    "portfolio_vega_before",
    "portfolio_vega_after",
    "portfolio_vega_change",
    "mode",
    "plan_reasons",
    "blocked_by",
    "operator_action",
    "operator_notes",
]
