"""Sheet schemas for the lean Kamandal V2 cockpit."""

from __future__ import annotations

UNIVERSE_HEADER = [
    "symbol",
    "enabled",
    "profile",
    "tradable_iv_percentile_min",
    "tradable_iv_percentile_max",
    "max_bpr_pct",
    "max_positions",
    "earnings_sensitive",
    "event_avoid_days_before",
    "event_avoid_days_after",
    "allowed_playbooks",
    "tier",
    "proposal_source",
    "proposal_reason",
    "proposal_date",
    "notes",
]

PLAYBOOKS_HEADER = [
    "playbook_id",
    "enabled",
    "strategy_family",
    "structure",
    "variant",
    "leg_count",
    "profiles",
    "applicable_direction",
    "applicable_thesis_tags",
    "applicable_horizon_min",
    "applicable_horizon_max",
    "iv_percentile_min",
    "iv_percentile_max",
    "iv_rank_min",
    "iv_rank_max",
    "iv_abs_min",
    "iv_abs_max",
    "earnings_blackout_days",
    "dte_min",
    "dte_max",
    "long_dte_min",
    "long_dte_max",
    "short_delta_min",
    "short_delta_max",
    "long_delta_min",
    "long_delta_max",
    "spread_width",
    "legs_extra",
    "min_credit_to_width_ratio",
    "max_debit_pct_bpr",
    "max_bid_ask_pct",
    "min_option_oi",
    "profit_target_pct",
    "max_loss_multiple",
    "exit_dte_min",
    "half_time_exit",
    "avoid_earnings",
    "exit_pre_event_days",
    "sizing_method",
    "sizing_value",
    "max_contracts",
    "live_max_bpr_per_order",
    "score_weight_credit",
    "score_weight_pop",
    "score_weight_liquidity",
    "score_weight_spread",
    "priority",
    "rationale",
    "notes",
    "universe_expansion_enabled",
    "underlying_price_min",
    "underlying_price_max",
    "csa_stage",
    "source_mode",
    "management_policy_json",
    # Unified-engine controls are appended so the protected migration preserves
    # every legacy column position, validation, and formula.
    "mode",
    "management_delta_target",
    "management_delta_max",
    "tested_side_confirmations",
    "rearm_inside_confirmations",
    "filled_side_adjustment_limit",
    "dte_action",
    "dte_action_threshold",
    "duration_roll_limit",
    "inversion_enabled",
    "event_timing",
    "event_near_expiry_after_days",
    "paired_order_required",
    "post_event_exit",
    # One-brain/multiple-venue controls. These remain appended so legacy
    # columns and formulas keep their exact positions.
    "execution_venue",
    "target_dte",
    # Retired 2026-08-30. Preserve these inert columns so the operator Sheet's
    # appended schema and every later column retain their established positions.
    "range_gate_required",
    "range_gate_max_age_days",
    "loss_close_multiple",
    # Explicit diagonal entry economics. Appended so every existing column
    # retains its position, validation, and formatting.
    "max_debit_to_width_ratio",
    # Exact-package sources are explicitly allowlisted per shadow playbook.
    "source_profiles",
    # Resting-profit economics are operator-owned and frozen on lifecycle open.
    # Runtime mode flags remain upper-bound kill switches only.
    "resting_profit_enabled",
    "resting_profit_arm_progress_pct",
    # Source-neutral input acceptance. Appended to preserve every deployed
    # playbook column position and formula.
    "accepted_inputs",
]

TRADE_SOURCES_HEADER = [
    "source_id",
    "output_kind",
    "mode",
    "notes",
]

TRADE_SOURCE_ACTIVITY_HEADER = [
    "observed_at",
    "source_id",
    "source_url",
    "classification",
    "interpretation",
    "planner_disposition",
    "effective_mode",
    "reason",
    "lifecycle_status",
    "symbol",
    "structure",
    "action",
    "evidence_status",
    "capability_support",
    "last_update",
    "post_ref",
    "output_id",
    "lifecycle_ids",
    "acquisition_status",
    "link_status",
    "interpretation_confidence",
    "normalized_output",
]

DAILY_PLAN_HEADER = [
    "plan_date",
    "plan_rank",
    "plan_id",
    "plan_status",
    "plan_trade_count",
    "plan_score",
    "plan_summary",
    "trade_bundle",
    "trade_bundle_json",
    "plan_total_bpr",
    "plan_bpr_utilization_pct",
    "buying_power_after",
    "portfolio_delta_before",
    "portfolio_delta_after",
    "portfolio_delta_change",
    "portfolio_gamma_before",
    "portfolio_gamma_after",
    "portfolio_gamma_change",
    "portfolio_theta_before",
    "portfolio_theta_after",
    "portfolio_theta_change",
    "portfolio_vega_before",
    "portfolio_vega_after",
    "portfolio_vega_change",
    "mode",
    "plan_reasons",
    "blocked_by",
    "plan_metrics_json",
    "plan_detail_json",
    "operator_action",
    "operator_notes",
]

MY_IDEAS_HEADER = [
    "date",
    "ticker",
    "type_of_trade",
    "direction",
    "horizon_days",
    "notes",
    "conviction",
    "status",
    "idea_id",
    "imported_at",
]

LIVE_BOOK_HEADER = [
    "updated_at_cst",
    "symbol",
    "structure",
    "playbook_id",
    "group_id",
    "entry_date",
    "dte",
    "entry_kind",
    "entry_credit_debit",
    "current_mark",
    "unrealized_pnl",
    "target_profit",
    "loss_threshold",
    "mfe",
    "mae",
    "working_open_orders",
    "working_close_orders",
    "last_close_attempt",
    "last_preflight_result",
    "broker_error_code",
    "reconciliation_status",
    "management_blocker",
    "recommended_action",
    "quote_fresh",
    "target_progress_pct",
    "report_json",
]
